version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: metropulse_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: dwh
      POSTGRES_USER: dwh
      POSTGRES_PASSWORD: dwhpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-04-18T19-09-19Z
    container_name: metropulse_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  minio-mc:
    image: minio/mc:RELEASE.2024-04-18T19-09-19Z
    container_name: metropulse_mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 admin admin123;
      mc mb -p local/raw;
      mc mb -p local/processed;
      mc anonymous set download local/raw;
      tail -f /dev/null
      "

  spark-master:
    image: bitnami/spark:3.5
    container_name: metropulse_spark_master
    environment:
      SPARK_MODE: master
      SPARK_RPC_PORT: 7077
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8080
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./spark_jobs:/opt/spark_jobs
      - ./data:/data
    depends_on:
      - minio

  spark-worker:
    image: bitnami/spark:3.5
    container_name: metropulse_spark_worker
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2
    ports:
      - "8081:8081"
    volumes:
      - ./spark_jobs:/opt/spark_jobs
      - ./data:/data
    depends_on:
      - spark-master

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: metropulse_ch
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9009:9009"
    volumes:
      - ch_data:/var/lib/clickhouse
      - ch_logs:/var/log/clickhouse-server

volumes:
  pgdata:
  minio_data:
  ch_data:
  ch_logs:

